# Generated by Django 3.0.9 on 2020-08-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField(default='2020-08-28')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-08-28')),
                ('due_date', models.DateField(default='2020-08-28')),
                ('user', models.CharField(max_length=50)),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='catalog.Category')),
                ('message', models.ManyToManyField(blank=True, to='catalog.Message')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
